### ISSUE TITLE
Les objets du bureau du directeur pointent a travers le réglement

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#11]
Duplicata du #94 de l'alpha, sensé être fermé mais toujours observé sur 1.00-p
![2021-05-25 12_58_34-Spellcaster University](https://user-images.githubusercontent.com/15092739/119492502-71940180-bd5f-11eb-8985-9b6439cdefe5.png)

**Comment by JulienNigon** [comment]
Scandaleux ! Que font les devs !

**Comment by Fouindor** [comment]
Bouh ! Pas content pas content !
On va jeter du caca sur les murs de l'école !
(mais plus sérieusement c'était pas un reproche, je me suis permis de le reposter parce qu'il était marqué comme fermé sur l'Alpha06/07)

**Comment by JulienNigon** [comment]
Tu as bien fait bien sûr :)
