### ISSUE TITLE
Carrière - Mort!

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#12]
1.00-p

Il faudrait peut-être filtrer et ne pas proposer certaines carrières négatives ? (je pense a Mort! et Tueur en Série par exemple)

![2021-05-25 13_41_35-Spellcaster University](https://user-images.githubusercontent.com/15092739/119492588-8a041c00-bd5f-11eb-90cf-ea6589ef321f.png)

On peut dire que c'est une école... MORTELLE 
(YYYYYEEEEEEAH 😎)

**Comment by JulienNigon** [comment]
Ahah, excellent, je l'avais pas vu passer... oui il faut le virer celui là :/
