### ISSUE TITLE
Mentor permet d'obtenir des traits d'élèves ?

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#16]
1.00-p

Un de mes profs que j'ai fait devenir mentor à le trait courageux... normal ?

![2021-05-25 13_54_33-Spellcaster University](https://user-images.githubusercontent.com/15092739/119526206-79fc3480-bd7f-11eb-95d8-c76fd96c58ef.png)

**Comment by MlleMau** [comment]
Bonsoir Fouindor,

Les professeurs peuvent quand même combattre lorsque des orcs, des squelettes, des chevaliers ou des inquisiteurs t'attaquent parce que tu as une mauvaise réputation avec eux. Je suppose que c'est pour cela que le trait est valide.

**Comment by JulienNigon** [comment]
En effet, MlleMau a raison.
Mais c'est vrai que le texte d'ambiance est trompeur, et le bonus ne sert pas en donjon...
