### ISSUE TITLE
Pentacle et professeurs

### ISSUE THREAD

**Issue by Tioy0** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#18]
Le pentacle semble toujours donner le trait "disciple de l'ombre" aux professeurs 
![disciple](https://user-images.githubusercontent.com/70773076/119896328-2afcfd80-bf3f-11eb-970b-d39c5ac8477c.JPG)

**Comment by Tioy0** [comment]
Le reliquaire applique aussi son bonus aux professeurs

**Comment by JulienNigon** [comment]
Merci.
On peine à s'en débarasser de celui-là.
