### ISSUE TITLE
Affichage du nombre de cartes déjà jouées

### ISSUE THREAD

**Issue by Tioy0** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#19]
Je sais pas si c'est voulu ou pas, mais actuellement l'icone qui indique le nombre de fois où une carte a été joué affiche des valeurs incorrectes dans les cas (que j'ai rencontré) suivants : 
-déplacement d'un artefact augmente ce nombre d'autant de fois que l'artefact a été déplacé.
-Si une carte est mise à la corbeille

Si c'est voulu de votre part, je trouve pas ça très logique car ça peut induire en erreur : distinction cartes jouées/cartes passées en main

Voila :)

**Comment by JulienNigon** [comment]
Merci :) Ce n'est absolument pas voulu !
