### ISSUE TITLE
Les enseignants restent bloqués sur place

### ISSUE THREAD

**Issue by Floue** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#2]
Les enseignants se bloquent régulièrement sur place (en continuant l'animation de marche).
Pour l'instant je n'ai repéré le bug que sur des enseignants  remplissant ces conditions :

- leurs jauges de besoin sont "hautes". C'est-à-dire qu'ils sont reposés / Sanité haute / etc.
- ils se bloquent systématiquement à un "spot enseignant", l'endroit dans une salle où ils enseignent globalement

![StuckyStucky](https://user-images.githubusercontent.com/6064776/118160452-9c588e80-b41e-11eb-881f-1b9b221aac6d.png)
Dans la capture en bas à droite, l'enseignant sortait de la salle de repos avec un lit et s'est directement bloqué, j'ai voulu voir si le deuxième enseignant allait se bloquer également mais il a bien pris le virage à gauche pour sortir de la pièce.

Un retour au menu, puis à la sauvegarde corrige le bug et les enseignants démarrent immédiatement leurs cours (sauf dans le cas de la salle "Private Apartments".

**Comment by MlleMau** [comment]
J'ai eu un professeur bloqué dans les appartements privés comme toi, et un professeur de nécromancie bloqué devant son pupitre également. Bien vu, Floue ! Un retour au menu et relancer la partie permet de le débloquer, sinon.

Edit : Déjà 5 fois que je relance, c'est TOUJOURS le professeur de nécromancie qui se bloque au même endroit, il doit être maudit x)

**Comment by MlleMau** [comment]
Nouveau cas !
Deux professeurs sont restés bloqués à cause d'un incendie, je pense que l'un allait l'éteindre quand l'autre passait, ils sont entrés en collision et ont voulu voir qui était le plus fort. J'ai attendu pour voir si un autre professeur viendrait éteindre l'incendie, mais aucun ne s'est dévoué. J'ai utilisé une Potion du vide et, magie ! Ils ont été débloqués. 

![Bug professeur bloqué](https://user-images.githubusercontent.com/60859116/118378173-2137d980-b5d2-11eb-9cc0-c701cc127245.jpg)

**Comment by MlleMau** [comment]
Mais ils me trollent, ces professeurs !
Le professeur de nécromancie (encore lui !) en a eu marre que je parvienne à le débloquer et a donc décider de faire les cent pas au lieu du sur-place. Il fait des allers-retours, toujours depuis son pupitre. Cette fois-ci, relancer la partie n'a pas suffit à le débloquer.
Un autre professeur (enfin, le conseiller d'orientation) s'est mis à faire les cent pas également.
Pendant ce temps, d'autres professeurs se bloquaient, et je relançais régulièrement la partie. Cela ne débloquait pas nos deux trolls. Et là, paf, au moment où je me dis que je relance pour la dernière fois de la soirée avant d'éteindre, le professeur de nécromancie a cessé de tourner en rond ! Il aura fallu au moins 5 relances pour qu'il se décide, lui.

**Comment by Neelan22** [comment]
le bug a été corrigé de notre côté, la mise à jour arrivera bientot. Merci pour vos retours :)

**Comment by JulienNigon** [comment]
Oui merci beaucoup ! C'était un gros bug ces professeurs trolls. Merci pour les retours ça nous a permis d'isoler le problème :)
