### ISSUE TITLE
Evenement fin d'année

### ISSUE THREAD

**Issue by Tioy0** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#21]
En durée de partie Marathon (et difficulté archimage), l'évenement "les armées du mal se rapprochent" se déclenche bien trop tôt, potentiellement comme lors d'une partie de durée normale : 
![annee11](https://user-images.githubusercontent.com/70773076/120084926-91675480-c0d4-11eb-9a9b-b88862132655.JPG)

**Comment by Tioy0** [comment]
version 1.00p au fait pour mes commentaires sorry

**Comment by JulienNigon** [comment]
Merci :)
Il ne me plait pas du tout ce bug :/
