### ISSUE TITLE
Incohérence dans les ressources requises pour piocher

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#23]
v1.00-x

Je ne sais pas ce qui délanche ça...

Ici, le coût affiché est de 237 mais ça me coûte en fait environ 250 de piocher:
![20210531164347_1](https://user-images.githubusercontent.com/15092739/120210492-22067780-c230-11eb-8f1c-5b174b3c15af.jpg)
![20210531164322_1](https://user-images.githubusercontent.com/15092739/120210493-229f0e00-c230-11eb-874a-1147cbddadac.jpg)

Ici, un coût inférieur au coût réel est affiché:
![20210531164325_1](https://user-images.githubusercontent.com/15092739/120210497-229f0e00-c230-11eb-8a50-138dbd904aa4.jpg)

dès que je recharge, tout revient dans l'ordre...
![20210531164505_1](https://user-images.githubusercontent.com/15092739/120210669-55e19d00-c230-11eb-88c1-a7090bfcd596.jpg)

[save.zip](https://github.com/JulienNigon/SpellcasterUniversityPrivateBetaExtended/files/6570960/save.zip)

**Comment by Tioy0** [comment]
Ça m'est arrivé il me semble aussi, je soupçonne un lien avec le bonus de réputation des orcs (+75 = -5% coût des cartes) : lorsque tu perds ou gagnes ce bonus, je me demande si il ne reste pas affiché ou une histoire du genre.

250 - 5% = 237,5 donc ça colle
