### ISSUE TITLE
Bug d'affichage des équipements

### ISSUE THREAD

**Issue by MlleMau** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#25]
Bonjour !

Je viens de remarquer un bug d'affichage plutôt étrange en me rendant dans le livre des statistiques. A la place des équipements, hé bien... voyez par vous-même.

![Bug affichage des équipements](https://user-images.githubusercontent.com/60859116/120515778-f241a600-c3ce-11eb-9c57-5cb42b0d9ade.jpg)

De plus, le Plastron sauvage et le Signe des Tres Anciens n'apparaissent pas dans ma liste, alors que mes élèves en sont bien équipés et que lors d'un choix de cartes, les précédentes sont bien comptées. Il ne s'agit donc bien que d'un bug d'affichage.

Bon courage à vous !
Maureen.

**Comment by JulienNigon** [comment]
Merci beaucoup :)
On a trouvé le problème ! Il était situé entre la chaise et l'écran du dev :D. Corrigé pour la prochaine mise à jour.
