### ISSUE TITLE
SdT + Collection de boules de cristal

### ISSUE THREAD

**Issue by MlleMau** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#3]
Bonjour !

Dans une Salle des Trophées, j'ai placé une « Collection de boules de cristal ». L'association a été trop efficace. Les 4 professeurs des salles attenantes ne gagnent plus rien, ni fatigue ni faim. 

![Bug collection de boules de cristal](https://user-images.githubusercontent.com/60859116/118376839-bc2cb580-b5ca-11eb-866b-98a513a2535b.jpg)

Bon courage à vous,
Maureen.

**Comment by JulienNigon** [comment]
Merci ! Il risque de ne pas être simple à corriger celui là ^^
