### ISSUE TITLE
Bug de placement lié au Belvédère

### ISSUE THREAD

**Issue by MlleMau** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#4]
Bonsoir,

Possédant déjà un belvédère, j'ai été surprise de voir que je pouvais placer un Réfectoire lumineux à côté, sur la partie inférieure. Un screen parlera mieux de lui-même : 

![Bug placement belvédere](https://user-images.githubusercontent.com/60859116/118379367-27ca4f00-b5da-11eb-9c9b-cc598eb9f9b7.jpg)

Comme vous le voyez, ce placement devrait être impossible. Je l'ai tout de même fait, pour voir jusqu'où irais le bug : les professeurs pourront-ils vraiment s'y rendre ? Non, aucun n'y est allé, la salle est bien inaccessible.

Bon courage,
Maureen.

**Comment by Neelan22** [comment]
bien vu ! merci
