### ISSUE TITLE
EN - Deux avenirs ont le même nom

### ISSUE THREAD

**Issue by ThreePandasInACoat** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#42]
Je joue en anglais par habitude (la localisation du jeu est géniale d'ailleurs !) et dans mon run spécial avenirs, j'ai été perturbée un bon moment par ce souci : 
![shsh](https://user-images.githubusercontent.com/86322427/122985490-8be0ef80-d39e-11eb-95b8-c836d1f1a91a.jpg)

Après un tour sur le wiki j'ai l'impression que dans la beta c'était "Metamorph" et "Shapeshifter" ?

**Comment by JulienNigon** [comment]
Oui, bien vu ! C'était bien ça.
On est passé à une traduction anglaise plus pro, mais cette petite coquille est passée.
