### ISSUE TITLE
Avenir radieux - 4ème objectif ?

### ISSUE THREAD

**Issue by MlleMau** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#6]
Bonsoir !

Sur mon deuxième tableau, j'ai constaté un bug lié à la quête « Avenir radieux ». J'avais déjà accepté 3 objectifs, et celui-ci m'a quand même été proposé. J'ai été obligée de donner une réponse. Ça n'a pas changé mes objectifs en cours, à voir à la fin du tableau si ça compte quand même.
L'inconvénient est que l'avenir lié à l'objectif que j'ai choisi est d'office mis en 100% lors du choix d'avenir de l'étudiant diplômé. Quand un archimage me passera sous le nez à cause de ça, j'en aurais gros ahah !

![Bug sur avenir radieux](https://user-images.githubusercontent.com/60859116/118552715-94228b00-b75f-11eb-8fad-7ab414c455b9.jpg)

Bon courage !
Maureen.

**Comment by JulienNigon** [comment]
Merci, ce devrait être corrigé dans la nouvelle version !
