### ISSUE TITLE
Mineur - Brûlez les livres ! 

### ISSUE THREAD

**Issue by MlleMau** [JulienNigon/SpellcasterUniversityPrivateBetaExtended#7]
Bonsoir,

Je peux maintenant vous confirmer un bug mineur concernant la suite d'événements de l'Inquisiteur, qui demande de brûler des livres. Lorsque la première étape apparaît et que je décide de brûler, le retrait de la carte et le gain de réputation se font bien, mais je n'ai pas les autres étapes. 

Dommage, mon événement préféré </3 ! 

Et bonne soirée,
Maureen.

**Comment by JulienNigon** [comment]
Super merci, ça sera corrigé pour le prochain patch.

C'est notre musicos qui l'a écrit, je lui dirai ça lui fera plaisir :)
